config/routes.rb
Rails.application.routes.draw do
  root "pokemons#index"
  resources :pokemons, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokeball.rb
class Pokeball < ApplicationRecord
  belongs_to :trainer
  belongs_to :pokemon

  validates :caught_on, presence: true
  validates :location, presence: true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_many :pokeballs
  has_many :trainers, through: :pokeballs
  has_one_attached :photo
end

app/models/trainer.rb
class Trainer < ApplicationRecord
  has_many :pokeballs
  has_many :pokemons, through: :pokeballs
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    @pokemons = Pokemon.all
  end

  def show
    @pokemon = Pokemon.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Pokemon" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :application, "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pokemons/index.html.erb
<h1>Liste des Pokémons</h1>

link for trainers
link for random pokemon
search bar for pokemon


<div class="grid">
  <% @pokemons.each do |pokemon| %>
    <div class="pokemon-card">
      <%= cl_image_tag pokemon.photo.key %>
      <h2><%= link_to pokemon.name.capitalize, pokemon_path(pokemon) %></h2>
      (<%= pokemon.element_type.capitalize %>)
    </div>
  <% end %>
</div>

app/views/pokemons/show.html.erb
<header class="header">
  <%= link_to "< Pokédex", root_path %>
</header>

<h1>Show me <%= @pokemon.name %></h1>
<%= @pokemon.element_type%>
<%= cl_image_tag @pokemon.photo.key %>